/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AttendanceSession {
  'id' : bigint,
  'startedAt' : [] | [bigint],
  'endedAt' : [] | [bigint],
  'date' : string,
  'isOpen' : boolean,
  'classId' : bigint,
}
export interface Class {
  'id' : bigint,
  'gps' : Location,
  'subject' : string,
  'name' : string,
  'isActive' : boolean,
  'teacherId' : Principal,
  'timeSlot' : TimeSlot,
  'enrolledStudentIds' : Array<string>,
}
export type DaysOfWeek = { 'tuesday' : null } |
  { 'wednesday' : null } |
  { 'saturday' : null } |
  { 'thursday' : null } |
  { 'sunday' : null } |
  { 'friday' : null } |
  { 'monday' : null };
export interface Location {
  'latitude' : number,
  'longitude' : number,
  'radiusMeters' : number,
}
export interface StudentProfile {
  'name' : string,
  'pinHashed' : string,
  'rollNumber' : string,
  'enrolledClassIds' : Array<bigint>,
  'facePhotoUrl' : [] | [string],
}
export interface TimeSlot {
  'startTime' : bigint,
  'endTime' : bigint,
  'daysOfWeek' : Array<DaysOfWeek>,
}
export interface UserProfile { 'name' : string, 'role' : UserRole }
export type UserRole = { 'teacher' : string } |
  { 'student' : string };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'createClass' : ActorMethod<[string, string, Location, TimeSlot], bigint>,
  'deleteClass' : ActorMethod<[bigint], undefined>,
  'enrollStudent' : ActorMethod<[bigint, string], undefined>,
  'getAttendanceSession' : ActorMethod<[bigint], [] | [AttendanceSession]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getClass' : ActorMethod<[bigint], [] | [Class]>,
  'getClassAttendanceReport' : ActorMethod<[bigint], string>,
  'getStudent' : ActorMethod<[string], [] | [StudentProfile]>,
  'getStudentAttendanceReport' : ActorMethod<[string], string>,
  'getStudentDashboard' : ActorMethod<[], string>,
  'getTeacherDashboardStats' : ActorMethod<[], string>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markAttendance' : ActorMethod<
    [bigint, number, number, string, string],
    undefined
  >,
  'registerStudent' : ActorMethod<[string, string, string], undefined>,
  'registerTeacher' : ActorMethod<[string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'startAttendanceSession' : ActorMethod<[bigint, string], bigint>,
  'stopAttendanceSession' : ActorMethod<[bigint], undefined>,
  'unenrollStudent' : ActorMethod<[bigint, string], undefined>,
  'updateClass' : ActorMethod<
    [bigint, string, string, Location, TimeSlot, boolean],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];