/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Location = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
  'radiusMeters' : IDL.Float64,
});
export const DaysOfWeek = IDL.Variant({
  'tuesday' : IDL.Null,
  'wednesday' : IDL.Null,
  'saturday' : IDL.Null,
  'thursday' : IDL.Null,
  'sunday' : IDL.Null,
  'friday' : IDL.Null,
  'monday' : IDL.Null,
});
export const TimeSlot = IDL.Record({
  'startTime' : IDL.Nat,
  'endTime' : IDL.Nat,
  'daysOfWeek' : IDL.Vec(DaysOfWeek),
});
export const AttendanceSession = IDL.Record({
  'id' : IDL.Nat,
  'startedAt' : IDL.Opt(IDL.Int),
  'endedAt' : IDL.Opt(IDL.Int),
  'date' : IDL.Text,
  'isOpen' : IDL.Bool,
  'classId' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'teacher' : IDL.Text,
  'student' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : UserRole });
export const Class = IDL.Record({
  'id' : IDL.Nat,
  'gps' : Location,
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
  'teacherId' : IDL.Principal,
  'timeSlot' : TimeSlot,
  'enrolledStudentIds' : IDL.Vec(IDL.Text),
});
export const StudentProfile = IDL.Record({
  'name' : IDL.Text,
  'pinHashed' : IDL.Text,
  'rollNumber' : IDL.Text,
  'enrolledClassIds' : IDL.Vec(IDL.Nat),
  'facePhotoUrl' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'createClass' : IDL.Func(
      [IDL.Text, IDL.Text, Location, TimeSlot],
      [IDL.Nat],
      [],
    ),
  'deleteClass' : IDL.Func([IDL.Nat], [], []),
  'enrollStudent' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'getAttendanceSession' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(AttendanceSession)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getClass' : IDL.Func([IDL.Nat], [IDL.Opt(Class)], ['query']),
  'getClassAttendanceReport' : IDL.Func([IDL.Nat], [IDL.Text], ['query']),
  'getStudent' : IDL.Func([IDL.Text], [IDL.Opt(StudentProfile)], ['query']),
  'getStudentAttendanceReport' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getStudentDashboard' : IDL.Func([], [IDL.Text], ['query']),
  'getTeacherDashboardStats' : IDL.Func([], [IDL.Text], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markAttendance' : IDL.Func(
      [IDL.Nat, IDL.Float64, IDL.Float64, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'registerStudent' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'registerTeacher' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'startAttendanceSession' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
  'stopAttendanceSession' : IDL.Func([IDL.Nat], [], []),
  'unenrollStudent' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateClass' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, Location, TimeSlot, IDL.Bool],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Location = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
    'radiusMeters' : IDL.Float64,
  });
  const DaysOfWeek = IDL.Variant({
    'tuesday' : IDL.Null,
    'wednesday' : IDL.Null,
    'saturday' : IDL.Null,
    'thursday' : IDL.Null,
    'sunday' : IDL.Null,
    'friday' : IDL.Null,
    'monday' : IDL.Null,
  });
  const TimeSlot = IDL.Record({
    'startTime' : IDL.Nat,
    'endTime' : IDL.Nat,
    'daysOfWeek' : IDL.Vec(DaysOfWeek),
  });
  const AttendanceSession = IDL.Record({
    'id' : IDL.Nat,
    'startedAt' : IDL.Opt(IDL.Int),
    'endedAt' : IDL.Opt(IDL.Int),
    'date' : IDL.Text,
    'isOpen' : IDL.Bool,
    'classId' : IDL.Nat,
  });
  const UserRole = IDL.Variant({ 'teacher' : IDL.Text, 'student' : IDL.Text });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : UserRole });
  const Class = IDL.Record({
    'id' : IDL.Nat,
    'gps' : Location,
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
    'teacherId' : IDL.Principal,
    'timeSlot' : TimeSlot,
    'enrolledStudentIds' : IDL.Vec(IDL.Text),
  });
  const StudentProfile = IDL.Record({
    'name' : IDL.Text,
    'pinHashed' : IDL.Text,
    'rollNumber' : IDL.Text,
    'enrolledClassIds' : IDL.Vec(IDL.Nat),
    'facePhotoUrl' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'createClass' : IDL.Func(
        [IDL.Text, IDL.Text, Location, TimeSlot],
        [IDL.Nat],
        [],
      ),
    'deleteClass' : IDL.Func([IDL.Nat], [], []),
    'enrollStudent' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'getAttendanceSession' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(AttendanceSession)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getClass' : IDL.Func([IDL.Nat], [IDL.Opt(Class)], ['query']),
    'getClassAttendanceReport' : IDL.Func([IDL.Nat], [IDL.Text], ['query']),
    'getStudent' : IDL.Func([IDL.Text], [IDL.Opt(StudentProfile)], ['query']),
    'getStudentAttendanceReport' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getStudentDashboard' : IDL.Func([], [IDL.Text], ['query']),
    'getTeacherDashboardStats' : IDL.Func([], [IDL.Text], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markAttendance' : IDL.Func(
        [IDL.Nat, IDL.Float64, IDL.Float64, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'registerStudent' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'registerTeacher' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'startAttendanceSession' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
    'stopAttendanceSession' : IDL.Func([IDL.Nat], [], []),
    'unenrollStudent' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateClass' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, Location, TimeSlot, IDL.Bool],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };