/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Location {
    latitude: number;
    longitude: number;
    radiusMeters: number;
}
export interface Class {
    id: bigint;
    gps: Location;
    subject: string;
    name: string;
    isActive: boolean;
    teacherId: Principal;
    timeSlot: TimeSlot;
    enrolledStudentIds: Array<string>;
}
export interface TimeSlot {
    startTime: bigint;
    endTime: bigint;
    daysOfWeek: Array<DaysOfWeek>;
}
export interface StudentProfile {
    name: string;
    pinHashed: string;
    rollNumber: string;
    enrolledClassIds: Array<bigint>;
    facePhotoUrl?: string;
}
export interface AttendanceSession {
    id: bigint;
    startedAt?: bigint;
    endedAt?: bigint;
    date: string;
    isOpen: boolean;
    classId: bigint;
}
export type UserRole = {
    __kind__: "teacher";
    teacher: string;
} | {
    __kind__: "student";
    student: string;
};
export interface UserProfile {
    name: string;
    role: UserRole;
}
export enum DaysOfWeek {
    tuesday = "tuesday",
    wednesday = "wednesday",
    saturday = "saturday",
    thursday = "thursday",
    sunday = "sunday",
    friday = "friday",
    monday = "monday"
}
export enum UserRole__1 {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole__1): Promise<void>;
    createClass(name: string, subject: string, gps: Location, timeSlot: TimeSlot): Promise<bigint>;
    deleteClass(classId: bigint): Promise<void>;
    enrollStudent(classId: bigint, rollNumber: string): Promise<void>;
    getAttendanceSession(sessionId: bigint): Promise<AttendanceSession | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole__1>;
    getClass(classId: bigint): Promise<Class | null>;
    getClassAttendanceReport(classId: bigint): Promise<string>;
    getStudent(rollNumber: string): Promise<StudentProfile | null>;
    getStudentAttendanceReport(rollNumber: string): Promise<string>;
    getStudentDashboard(): Promise<string>;
    getTeacherDashboardStats(): Promise<string>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    markAttendance(sessionId: bigint, latitude: number, longitude: number, facePhotoSnapshot: string, pin: string): Promise<void>;
    registerStudent(rollNumber: string, name: string, pinHashed: string): Promise<void>;
    registerTeacher(username: string, passwordHashed: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    startAttendanceSession(classId: bigint, date: string): Promise<bigint>;
    stopAttendanceSession(sessionId: bigint): Promise<void>;
    unenrollStudent(classId: bigint, rollNumber: string): Promise<void>;
    updateClass(classId: bigint, name: string, subject: string, gps: Location, timeSlot: TimeSlot, isActive: boolean): Promise<void>;
}
import type { AttendanceSession as _AttendanceSession, Class as _Class, DaysOfWeek as _DaysOfWeek, Location as _Location, StudentProfile as _StudentProfile, TimeSlot as _TimeSlot, UserProfile as _UserProfile, UserRole as _UserRole, UserRole__1 as _UserRole__1 } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createClass(arg0: string, arg1: string, arg2: Location, arg3: TimeSlot): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createClass(arg0, arg1, arg2, to_candid_TimeSlot_n3(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createClass(arg0, arg1, arg2, to_candid_TimeSlot_n3(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async deleteClass(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteClass(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteClass(arg0);
            return result;
        }
    }
    async enrollStudent(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.enrollStudent(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.enrollStudent(arg0, arg1);
            return result;
        }
    }
    async getAttendanceSession(arg0: bigint): Promise<AttendanceSession | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttendanceSession(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttendanceSession(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole__1> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole__1_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole__1_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClass(arg0: bigint): Promise<Class | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getClass(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClass(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClassAttendanceReport(arg0: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getClassAttendanceReport(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClassAttendanceReport(arg0);
            return result;
        }
    }
    async getStudent(arg0: string): Promise<StudentProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudent(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudent(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudentAttendanceReport(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentAttendanceReport(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentAttendanceReport(arg0);
            return result;
        }
    }
    async getStudentDashboard(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentDashboard();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentDashboard();
            return result;
        }
    }
    async getTeacherDashboardStats(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeacherDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeacherDashboardStats();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markAttendance(arg0: bigint, arg1: number, arg2: number, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markAttendance(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAttendance(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async registerStudent(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerStudent(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerStudent(arg0, arg1, arg2);
            return result;
        }
    }
    async registerTeacher(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerTeacher(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerTeacher(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n31(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n31(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async startAttendanceSession(arg0: bigint, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.startAttendanceSession(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startAttendanceSession(arg0, arg1);
            return result;
        }
    }
    async stopAttendanceSession(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.stopAttendanceSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.stopAttendanceSession(arg0);
            return result;
        }
    }
    async unenrollStudent(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unenrollStudent(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unenrollStudent(arg0, arg1);
            return result;
        }
    }
    async updateClass(arg0: bigint, arg1: string, arg2: string, arg3: Location, arg4: TimeSlot, arg5: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateClass(arg0, arg1, arg2, arg3, to_candid_TimeSlot_n3(this._uploadFile, this._downloadFile, arg4), arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateClass(arg0, arg1, arg2, arg3, to_candid_TimeSlot_n3(this._uploadFile, this._downloadFile, arg4), arg5);
            return result;
        }
    }
}
function from_candid_AttendanceSession_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AttendanceSession): AttendanceSession {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Class_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Class): Class {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_DaysOfWeek_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DaysOfWeek): DaysOfWeek {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_StudentProfile_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StudentProfile): StudentProfile {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_TimeSlot_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TimeSlot): TimeSlot {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole__1_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole__1): UserRole__1 {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Class]): Class | null {
    return value.length === 0 ? null : from_candid_Class_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StudentProfile]): StudentProfile | null {
    return value.length === 0 ? null : from_candid_StudentProfile_n28(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AttendanceSession]): AttendanceSession | null {
    return value.length === 0 ? null : from_candid_AttendanceSession_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    startedAt: [] | [bigint];
    endedAt: [] | [bigint];
    date: string;
    isOpen: boolean;
    classId: bigint;
}): {
    id: bigint;
    startedAt?: bigint;
    endedAt?: bigint;
    date: string;
    isOpen: boolean;
    classId: bigint;
} {
    return {
        id: value.id,
        startedAt: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.startedAt)),
        endedAt: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.endedAt)),
        date: value.date,
        isOpen: value.isOpen,
        classId: value.classId
    };
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: _UserRole;
}): {
    name: string;
    role: UserRole;
} {
    return {
        name: value.name,
        role: from_candid_UserRole_n15(_uploadFile, _downloadFile, value.role)
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    gps: _Location;
    subject: string;
    name: string;
    isActive: boolean;
    teacherId: Principal;
    timeSlot: _TimeSlot;
    enrolledStudentIds: Array<string>;
}): {
    id: bigint;
    gps: Location;
    subject: string;
    name: string;
    isActive: boolean;
    teacherId: Principal;
    timeSlot: TimeSlot;
    enrolledStudentIds: Array<string>;
} {
    return {
        id: value.id,
        gps: value.gps,
        subject: value.subject,
        name: value.name,
        isActive: value.isActive,
        teacherId: value.teacherId,
        timeSlot: from_candid_TimeSlot_n22(_uploadFile, _downloadFile, value.timeSlot),
        enrolledStudentIds: value.enrolledStudentIds
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    startTime: bigint;
    endTime: bigint;
    daysOfWeek: Array<_DaysOfWeek>;
}): {
    startTime: bigint;
    endTime: bigint;
    daysOfWeek: Array<DaysOfWeek>;
} {
    return {
        startTime: value.startTime,
        endTime: value.endTime,
        daysOfWeek: from_candid_vec_n24(_uploadFile, _downloadFile, value.daysOfWeek)
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    pinHashed: string;
    rollNumber: string;
    enrolledClassIds: Array<bigint>;
    facePhotoUrl: [] | [string];
}): {
    name: string;
    pinHashed: string;
    rollNumber: string;
    enrolledClassIds: Array<bigint>;
    facePhotoUrl?: string;
} {
    return {
        name: value.name,
        pinHashed: value.pinHashed,
        rollNumber: value.rollNumber,
        enrolledClassIds: value.enrolledClassIds,
        facePhotoUrl: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.facePhotoUrl))
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    teacher: string;
} | {
    student: string;
}): {
    __kind__: "teacher";
    teacher: string;
} | {
    __kind__: "student";
    student: string;
} {
    return "teacher" in value ? {
        __kind__: "teacher",
        teacher: value.teacher
    } : "student" in value ? {
        __kind__: "student",
        student: value.student
    } : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole__1 {
    return "admin" in value ? UserRole__1.admin : "user" in value ? UserRole__1.user : "guest" in value ? UserRole__1.guest : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tuesday: null;
} | {
    wednesday: null;
} | {
    saturday: null;
} | {
    thursday: null;
} | {
    sunday: null;
} | {
    friday: null;
} | {
    monday: null;
}): DaysOfWeek {
    return "tuesday" in value ? DaysOfWeek.tuesday : "wednesday" in value ? DaysOfWeek.wednesday : "saturday" in value ? DaysOfWeek.saturday : "thursday" in value ? DaysOfWeek.thursday : "sunday" in value ? DaysOfWeek.sunday : "friday" in value ? DaysOfWeek.friday : "monday" in value ? DaysOfWeek.monday : value;
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DaysOfWeek>): Array<DaysOfWeek> {
    return value.map((x)=>from_candid_DaysOfWeek_n25(_uploadFile, _downloadFile, x));
}
function to_candid_DaysOfWeek_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DaysOfWeek): _DaysOfWeek {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_TimeSlot_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TimeSlot): _TimeSlot {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n32(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole__1_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): _UserRole__1 {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function to_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: UserRole;
}): {
    name: string;
    role: _UserRole;
} {
    return {
        name: value.name,
        role: to_candid_UserRole_n33(_uploadFile, _downloadFile, value.role)
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    startTime: bigint;
    endTime: bigint;
    daysOfWeek: Array<DaysOfWeek>;
}): {
    startTime: bigint;
    endTime: bigint;
    daysOfWeek: Array<_DaysOfWeek>;
} {
    return {
        startTime: value.startTime,
        endTime: value.endTime,
        daysOfWeek: to_candid_vec_n5(_uploadFile, _downloadFile, value.daysOfWeek)
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole__1.admin ? {
        admin: null
    } : value == UserRole__1.user ? {
        user: null
    } : value == UserRole__1.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "teacher";
    teacher: string;
} | {
    __kind__: "student";
    student: string;
}): {
    teacher: string;
} | {
    student: string;
} {
    return value.__kind__ === "teacher" ? {
        teacher: value.teacher
    } : value.__kind__ === "student" ? {
        student: value.student
    } : value;
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DaysOfWeek): {
    tuesday: null;
} | {
    wednesday: null;
} | {
    saturday: null;
} | {
    thursday: null;
} | {
    sunday: null;
} | {
    friday: null;
} | {
    monday: null;
} {
    return value == DaysOfWeek.tuesday ? {
        tuesday: null
    } : value == DaysOfWeek.wednesday ? {
        wednesday: null
    } : value == DaysOfWeek.saturday ? {
        saturday: null
    } : value == DaysOfWeek.thursday ? {
        thursday: null
    } : value == DaysOfWeek.sunday ? {
        sunday: null
    } : value == DaysOfWeek.friday ? {
        friday: null
    } : value == DaysOfWeek.monday ? {
        monday: null
    } : value;
}
function to_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<DaysOfWeek>): Array<_DaysOfWeek> {
    return value.map((x)=>to_candid_DaysOfWeek_n6(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
